// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwvx5bqR-zIp0xxRcnhFON7wBvF7z_IU',
    appId: '1:385117718811:web:ffd4b8001dddeae782ebbe',
    messagingSenderId: '385117718811',
    projectId: 'endimata-c7e11',
    authDomain: 'endimata-c7e11.firebaseapp.com',
    storageBucket: 'endimata-c7e11.firebasestorage.app',
    measurementId: 'G-B2MQ8WX2K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9eO6YLVFml-vvlJDcNaypKnyhMu_tds',
    appId: '1:385117718811:android:9195e592983bca0182ebbe',
    messagingSenderId: '385117718811',
    projectId: 'endimata-c7e11',
    storageBucket: 'endimata-c7e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQmTfttwATqCBwOsCo4MkXH9RW31hn-M',
    appId: '1:385117718811:ios:95199d15d16d485e82ebbe',
    messagingSenderId: '385117718811',
    projectId: 'endimata-c7e11',
    storageBucket: 'endimata-c7e11.firebasestorage.app',
    iosBundleId: 'com.pvpshk4.endimata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQmTfttwATqCBwOsCo4MkXH9RW31hn-M',
    appId: '1:385117718811:ios:95199d15d16d485e82ebbe',
    messagingSenderId: '385117718811',
    projectId: 'endimata-c7e11',
    storageBucket: 'endimata-c7e11.firebasestorage.app',
    iosBundleId: 'com.pvpshk4.endimata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlwvx5bqR-zIp0xxRcnhFON7wBvF7z_IU',
    appId: '1:385117718811:web:1a6f65915e4fafd882ebbe',
    messagingSenderId: '385117718811',
    projectId: 'endimata-c7e11',
    authDomain: 'endimata-c7e11.firebaseapp.com',
    storageBucket: 'endimata-c7e11.firebasestorage.app',
    measurementId: 'G-14808BXQLL',
  );
}
